@endpoint = fwtechexcelaisrch.search.windows.net
@AZURE_OPENAI_ENDPOINT = https://fwtechexcelaiaoai.openai.azure.com
@dataSourceName_pdf = pdf
@storageResourceId = /subscriptions/<subscription_id>/resourceGroups/rg-techexcelai/providers/Microsoft.Storage/storageAccounts/fwtechexcelaistr
@containerName = brochures
@indexName = pdf
### To set token use in same folder
### echo "AZURE_TOKEN=$(az account get-access-token --scope https://search.azure.com/.default | jq -r .'accessToken')" > .env
### echo "AZURE_OPENAI_API_KEY=$(az cognitiveservices account keys list --name $AZURE_OPENAI_SERVICE_NAME --resource-group $RESOURCE_GROUP --query key1 --output tsv)" >> .env
@token = {{$dotenv %AZURE_TOKEN}}
@AZURE_OPENAI_API_KEY = {{$dotenv %AZURE_OPENAI_API_KEY}}


### Create Datasource

PUT https://{{endpoint}}/datasources('{{indexName}}-datasource')?api-version=2024-07-01
Content-Type: application/json
Authorization: Bearer {{token}}
  
{
    "name" : "{{indexName}}-datasource",
    "type" : "azureblob",
    "credentials" : { "connectionString" : "ResourceId={{storageResourceId}};" },
    "container" : { "name" : "{{containerName}}", "query" : null }
}


### Create Index
POST https://{{endpoint}}/indexes?api-version=2024-07-01
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{indexName}}-index",
  "fields": [
    {
      "name": "chunk_id",
      "type": "Edm.String",
      "searchable": true,
      "filterable": false,
      "retrievable": true,
      "stored": true,
      "sortable": true,
      "facetable": false,
      "key": true,
      "analyzer": "keyword",
      "synonymMaps": []
    },
    {
      "name": "parent_id",
      "type": "Edm.String",
      "searchable": false,
      "filterable": true,
      "retrievable": true,
      "stored": true,
      "sortable": false,
      "facetable": false,
      "key": false,
      "synonymMaps": []
    },
    {
      "name": "chunk",
      "type": "Edm.String",
      "searchable": true,
      "filterable": false,
      "retrievable": true,
      "stored": true,
      "sortable": false,
      "facetable": false,
      "key": false,
      "synonymMaps": []
    },
    {
      "name": "title",
      "type": "Edm.String",
      "searchable": true,
      "filterable": false,
      "retrievable": true,
      "stored": true,
      "sortable": false,
      "facetable": false,
      "key": false,
      "synonymMaps": []
    },
    {
      "name": "text_vector",
      "type": "Collection(Edm.Single)",
      "searchable": true,
      "filterable": false,
      "retrievable": true,
      "stored": true,
      "sortable": false,
      "facetable": false,
      "key": false,
      "dimensions": 1536,
      "vectorSearchProfile": "{{indexName}}-azureOpenAi-text-profile",
      "synonymMaps": []
    }
  ],
  "scoringProfiles": [],
  "suggesters": [],
  "analyzers": [],
  "tokenizers": [],
  "tokenFilters": [],
  "charFilters": [],
  "similarity": {
    "@odata.type": "#Microsoft.Azure.Search.BM25Similarity"
  },
  "semantic": {
    "defaultConfiguration": "{{indexName}}-semantic-configuration",
    "configurations": [
      {
        "name": "{{indexName}}-semantic-configuration",
        "prioritizedFields": {
          "titleField": {
            "fieldName": "title"
          },
          "prioritizedContentFields": [
            {
              "fieldName": "chunk"
            }
          ],
          "prioritizedKeywordsFields": []
        }
      }
    ]
  },
  "vectorSearch": {
    "algorithms": [
      {
        "name": "{{indexName}}-algorithm",
        "kind": "hnsw",
        "hnswParameters": {
          "metric": "cosine",
          "m": 4,
          "efConstruction": 400,
          "efSearch": 500
        }
      }
    ],
    "profiles": [
      {
        "name": "{{indexName}}-azureOpenAi-text-profile",
        "algorithm": "{{indexName}}-algorithm",
        "vectorizer": "{{indexName}}-azureOpenAi-text-vectorizer"
      }
    ],
    "vectorizers": [
      {
        "name": "{{indexName}}-azureOpenAi-text-vectorizer",
        "kind": "azureOpenAI",
        "azureOpenAIParameters": {
          "resourceUri": "{{AZURE_OPENAI_ENDPOINT}}",
          "deploymentId": "ada-embedding",
          "modelName": "text-embedding-ada-002"
        }
      }
    ],
    "compressions": []
  }
}

### Create Skillset
POST https://{{endpoint}}//skillsets?api-version=2024-07-01
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{indexName}}-skillset",
  "description": "Skillset to chunk documents and generate embeddings",
  "skills": [
    {
      "@odata.type": "#Microsoft.Skills.Text.SplitSkill",
      "name": "#1",
      "description": "Split skill to chunk documents",
      "context": "/document",
      "defaultLanguageCode": "en",
      "textSplitMode": "pages",
      "maximumPageLength": 2000,
      "pageOverlapLength": 500,
      "maximumPagesToTake": 0,
      "inputs": [
        {
          "name": "text",
          "source": "/document/content",
          "inputs": []
        }
      ],
      "outputs": [
        {
          "name": "textItems",
          "targetName": "pages"
        }
      ]
    },
    {
      "@odata.type": "#Microsoft.Skills.Text.AzureOpenAIEmbeddingSkill",
      "name": "#2",
      "context": "/document/pages/*",
      "resourceUri": "{{AZURE_OPENAI_ENDPOINT}}",
      "deploymentId": "ada-embedding",
      "dimensions": 1536,
      "modelName": "text-embedding-ada-002",
      "inputs": [
        {
          "name": "text",
          "source": "/document/pages/*",
          "inputs": []
        }
      ],
      "outputs": [
        {
          "name": "embedding",
          "targetName": "text_vector"
        }
      ]
    }
  ],
  "indexProjections": {
    "selectors": [
      {
        "targetIndexName": "{{indexName}}-index",
        "parentKeyFieldName": "parent_id",
        "sourceContext": "/document/pages/*",
        "mappings": [
          {
            "name": "text_vector",
            "source": "/document/pages/*/text_vector",
            "inputs": []
          },
          {
            "name": "chunk",
            "source": "/document/pages/*",
            "inputs": []
          },
          {
            "name": "title",
            "source": "/document/title",
            "inputs": []
          }
        ]
      }
    ],
    "parameters": {
      "projectionMode": "skipIndexingParentDocuments"
    }
  }
}




### Create Indexer
POST https://{{endpoint}}/indexers?api-version=2024-07-01
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{indexName}}-indexer",
  "description": null,
  "dataSourceName": "{{indexName}}-datasource",
  "skillsetName": "{{indexName}}-skillset",
  "targetIndexName": "{{indexName}}-index",
  "disabled": null,
  "schedule": null,
  "parameters": {
    "batchSize": null,
    "maxFailedItems": null,
    "maxFailedItemsPerBatch": null,
    "base64EncodeKeys": null,
    "configuration": {
      "dataToExtract": "contentAndMetadata",
      "parsingMode": "default"
    }
  },
  "fieldMappings": [
    {
      "sourceFieldName": "metadata_storage_name",
      "targetFieldName": "title",
      "mappingFunction": null
    }
  ],
  "outputFieldMappings": [],
  "encryptionKey": null
}
